codemonkey_cv_varios:
    resource: "@CodemonkeyCVVariosBundle/Resources/config/routing.yml"
    host: varios.katanastudios.com
    prefix:   /

codemonkey_cv_website:
    resource: "@CodemonkeyCVWebsiteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
          _locale: "%app.locales%"