parameters:
#    codemonkey_cv_website.example.class: CodemonkeyCV\WebsiteBundle\Example

services:
#    codemonkey_cv_website.example:
#        class: %codemonkey_cv_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
